# Generated by Django 6.0.3 on 2026-04-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
