# Generated by Django 6.0.3 on 2026-04-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_birthday_user_gender_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
