# Generated by Django 6.0.3 on 2026-04-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_contactmessage_course_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.CharField(blank=True, help_text='Khoa/Trường đào tạo (VD: Trường Đại học Công nghệ)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='subject_code',
            field=models.CharField(blank=True, help_text='Mã môn học VNU (VD: INT3117)', max_length=20, null=True),
        ),
    ]
