# Generated by Django 6.0.3 on 2026-04-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, help_text='Thời gian học tính bằng giây'),
        ),
    ]
