# Generated by Django 6.0.3 on 2026-04-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courseannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='instructor_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
