# Generated by Django 6.0.3 on 2026-04-13 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_end_date_course_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='document_file',
            field=models.FileField(blank=True, help_text='Tài liệu đính kèm (PDF/Slide)', null=True, upload_to='lessons/documents/'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='draft_answers',
            field=models.JSONField(blank=True, help_text='Lưu URL JSON mảng ID các answer đã chọn tạm thời.', null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_submitted',
            field=models.BooleanField(default=True, help_text='Bài làm đã nộp hay mới lưu nháp'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='LessonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
