# Generated by Django 6.0.3 on 2026-04-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_faq_category_created_by_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('deadline', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('tuition', models.CharField(max_length=100)),
                ('logo', models.CharField(help_text="Tên viết tắt trường để frontend dựa vào render màu (VD: 'BK')", max_length=50)),
                ('instructor', models.CharField(blank=True, max_length=200, null=True)),
                ('instructor_title', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', models.JSONField(default=list, help_text='Danh sách kỹ năng (JSON array of strings)')),
                ('curriculum', models.JSONField(default=list, help_text='Chương trình học (JSON array of objects: {title, lessons})')),
                ('videos', models.JSONField(default=list, help_text='Video liên quan (JSON array of strings)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
